const CLASSES=['WHO','KNOW','THINK','CAN','MAY','ACT','DID'];
const QUESTIONS={WHO:'Who is acting?',KNOW:'What does it work with?',THINK:'How does it think or plan?',CAN:'What can it technically reach?',MAY:'What is it allowed to do?',ACT:'Where can real effects happen?',DID:'How is the result evidenced?'};
const $=(selector)=>document.querySelector(selector);
const form=$('#analyze-form'),repositoryInput=$('#repository'),analyzeButton=$('#analyze-button'),demoButton=$('#demo-button'),statusNode=$('#status'),errorNode=$('#error'),resultNode=$('#result'),resultTitle=$('#result-title'),scanMeta=$('#scan-meta'),partialWarning=$('#partial-warning'),storyView=$('#story-view'),inspectView=$('#inspect-view'),systemView=$('#system-view');
const tabs=[...document.querySelectorAll('.view-tab')];
function create(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function exampleIr(){const node=(semanticClass,label,evidence)=>({id:`${semanticClass.toLowerCase()}-example`,semanticClass,label,statement:`Example evidence for ${semanticClass}.`,evidenceState:'INFERRED',confidence:.8,evidence:[{path:evidence,line:12,snippet:`example ${label.toLowerCase()}`,detector:'demo'}]});return{avglVersion:'0.1',generatedAt:new Date().toISOString(),source:{kind:'repository',label:'example/review-agent'},analysis:{pipeline:['DISCOVER','CLASSIFY','BIND','PROJECT'],mode:'demo',filesSeen:38,filesScanned:17,skippedSensitive:['.env'],skippedOversize:[]},nodes:[node('WHO','Review agent / harness','src/agent.ts'),node('KNOW','Repository + issue context','src/context.ts'),node('THINK','Reasoning model + review loop','src/reviewer.ts'),node('CAN','Repository reader + test runner','src/tools.ts'),node('ACT','Named test execution','src/executor.ts'),node('DID','Test result + review evidence','src/evidence.ts')],relations:[],unknowns:['MAY'],invariants:['HARNESS != AUTHORITY','CONTEXT != PERMISSION','CAN != MAY','PROPOSAL != EXECUTION','ACT != DID','RECEIPT != VERIFICATION']}}
function byClass(ir,semanticClass){return ir.nodes.find((node)=>node.semanticClass===semanticClass)??null}
function answer(ir,semanticClass){return byClass(ir,semanticClass)?.label??'Not evidenced'}
function metaChip(text){return create('span','meta-chip',text)}
function storyStep(index,ir,semanticClass){const node=byClass(ir,semanticClass),wrapper=create('div',`story-step${node?'':' unknown'}`),body=create('div'),question=create('div','story-question');wrapper.append(create('div','story-number',String(index)));question.append(create('span','token',semanticClass),document.createTextNode(QUESTIONS[semanticClass]));body.append(question,create('p','story-answer',node?node.label:'Not evidenced'),create('p','story-explain',node?node.statement:'The bounded scan found no evidence strong enough to fill this part of the story.'));wrapper.append(body);return wrapper}
function renderStory(ir){storyView.replaceChildren();const stack=create('div','story-stack');stack.append(storyStep(1,ir,'WHO'),storyStep(2,ir,'KNOW'),storyStep(3,ir,'THINK'));const pair=create('div','capability-pair'),can=byClass(ir,'CAN'),may=byClass(ir,'MAY'),canCard=create('div','pair-card'),mayCard=create('div',`pair-card${may?'':' authority-missing'}`);canCard.append(create('span','token','CAN'),create('h3','',can?can.label:'Not evidenced'),create('p','',QUESTIONS.CAN));mayCard.append(create('span','token','MAY'),create('h3','',may?may.label:'Not evidenced'),create('p','',QUESTIONS.MAY));pair.append(canCard,mayCard);if(can&&!may)pair.append(create('p','invariant-note','Technical capability was found, but authority was not. AVGL keeps CAN and MAY separate.'));stack.append(pair,storyStep(4,ir,'ACT'),storyStep(5,ir,'DID'));storyView.append(stack)}
function renderInspect(ir){inspectView.replaceChildren();const grid=create('div','inspect-grid');for(const semanticClass of CLASSES){const node=byClass(ir,semanticClass),card=create('article','inspect-card'),head=create('div','inspect-card-head'),titleBox=create('div');titleBox.append(create('span','token',semanticClass),create('h3','',QUESTIONS[semanticClass]));head.append(titleBox,create('span','state-chip',node?.evidenceState??'UNKNOWN'));card.append(head,create('p','',node?node.label:'No bounded evidence found.'));if(node?.evidence?.length){const details=create('details'),list=create('ul','evidence-list');details.append(create('summary','',`${node.evidence.length} evidence reference${node.evidence.length===1?'':'s'}`));for(const evidence of node.evidence){const item=create('li','evidence-item');item.append(create('div','evidence-path',`${evidence.path}:${evidence.line}`),create('div','evidence-snippet',evidence.snippet||'(empty line)'));list.append(item)}details.append(list);card.append(details)}grid.append(card)}inspectView.append(grid)}
function systemBand(token,title,copy){const band=create('div','system-band');band.append(create('span','token',token),create('h3','',title),create('p','',copy));return band}
function arrow(){return create('div','system-arrow','↓')}
function renderSystem(ir){systemView.replaceChildren();const story=create('div','system-story'),boundary=create('div','system-boundary','Authority boundary'),pair=create('div','system-pair');story.append(systemBand('WHO · KNOW · THINK','Agent plane',`${answer(ir,'WHO')} · ${answer(ir,'KNOW')} · ${answer(ir,'THINK')}`),arrow(),systemBand('PROPOSAL','Intent leaves cognition','A model proposal is not yet authority or an external effect.'),arrow(),boundary);pair.append(systemBand('CAN',answer(ir,'CAN'),'Technical reach / callable surface'),systemBand('MAY',answer(ir,'MAY'),'Policy / permission / grant evidence'));story.append(pair,arrow(),systemBand('ACT',answer(ir,'ACT'),'Potential or observed effect path'),arrow(),systemBand('DID',answer(ir,'DID'),'Evidence / verification path'));systemView.append(story)}
function render(ir){resultTitle.textContent=ir.source?.label||'Repository';scanMeta.replaceChildren(metaChip(`${ir.analysis.filesScanned}/${ir.analysis.filesSeen} files scanned`),metaChip(`${ir.nodes.length}/7 classes evidenced`),metaChip(ir.analysis.mode));partialWarning.hidden=!String(ir.analysis.mode).includes('partial');renderStory(ir);renderInspect(ir);renderSystem(ir);resultNode.hidden=false;resultNode.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
function setBusy(busy,message=''){analyzeButton.disabled=busy;analyzeButton.textContent=busy?'Analyzing…':'Analyze';statusNode.textContent=message}
function showError(message){errorNode.textContent=message;errorNode.hidden=false}
function clearError(){errorNode.hidden=true;errorNode.textContent=''}
form.addEventListener('submit',async(event)=>{event.preventDefault();clearError();const repository=repositoryInput.value.trim();if(!repository)return;setBusy(true,'Reading bounded repository surfaces and binding evidence…');try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Analysis failed (${response.status}).`);render(payload.ir);statusNode.textContent='Analysis complete. Unknowns remain explicit.'}catch(error){showError(error?.message||'Analysis failed.');statusNode.textContent=''}finally{setBusy(false,statusNode.textContent)}});
demoButton.addEventListener('click',()=>{clearError();repositoryInput.value='example/review-agent';render(exampleIr());statusNode.textContent='Example loaded. MAY is intentionally unknown to demonstrate CAN ≠ MAY.'});
tabs.forEach((tab)=>tab.addEventListener('click',()=>{const view=tab.dataset.view;tabs.forEach((candidate)=>{const selected=candidate===tab;candidate.classList.toggle('active',selected);candidate.setAttribute('aria-selected',String(selected))});storyView.hidden=view!=='story';inspectView.hidden=view!=='inspect';systemView.hidden=view!=='system'}));
