const $=s=>document.querySelector(s);
const state={locale:localStorage.getItem("avgl.locale")||(navigator.language||"en").toLowerCase().startsWith("de")?"de":"en",scanStrategy:"full",repo:"",ir:null,inventory:null,activeFile:null,chat:[]};
const TXT={
en:{hero1:"Understand the agent.",hero2:"Not the graph.",hero:"Paste a public GitHub repository. AVGL maps bounded evidence into a readable system story, a hierarchical repository view, and an evidence-aware assistant.",repo:"GitHub repository",analyze:"Analyze",help:"v0.2 analyzes public GitHub repositories. Private repository auth is not enabled yet.",analysis:"Analysis",story:"Story",files:"Files",inspect:"Inspect",system:"System",filesTitle:"Repository structure",filesIntro:"Browse the repository by hierarchy. Select a file for a grounded description of its role, content, and likely effect.",search:"Search files…",select:"Select a file",selectHint:"AVGL will explain what it contains, what role it plays, and which semantic areas it touches.",excerpt:"Source excerpt",ask:"Ask AVGL",assistant:"Repository assistant",noRepo:"Analyze a repository first. The assistant will answer against the current repo context.",placeholder:"Ask about architecture, a file, permissions, runtime…",send:"Send",loading:"Discovering, binding and synthesizing repository evidence…",done:"Analysis complete. Signals are bounded; unknowns stay explicit.",loadFiles:"Loading repository hierarchy…",filesFail:"Repository hierarchy could not be loaded.",fileLoad:"Loading file context…",fileFail:"File context could not be loaded.",role:"Role",areas:"Semantic areas",symbols:"Symbols / exports",lines:"Lines",size:"Size",source:"Source surfaces",notFound:"Not evidenced",partial:"Partial bounded scan",complete:"Complete bounded scan",systemNote:"Semantic frame, not reconstructed topology. v0.2 does not yet extract complete relation/call paths.",evidenceIntro:"Static signals grouped by semantic area. Documentation can support understanding, but cannot by itself prove MAY, ACT or DID.",thinking:"Reading relevant repository context…",chatFail:"The assistant could not answer this request.",keyMissing:"OpenRouter is not configured. Add OPENROUTER_API_KEY in Vercel.",suggest1:"What are the biggest architecture gaps?",suggest2:"Explain the authority model.",suggest3:"Which files matter most for runtime behavior?",canMay:"Technical reach is not permission.",actDid:"An effect path is not a verified result.",unknown:"Missing evidence is never filled with a guess.",scanModeLabel:"Scan mode",scanFull:"Full",scanQuick:"Quick · 120",scanFullHint:"Scans every eligible text/code file in the complete Git tree.",scanQuickHint:"Fast weighted sample of up to 120 eligible files.",sampled:"files scanned",fullScan:"Full source scan",quickScan:"Quick sample"},
de:{hero1:"Verstehe den Agent.",hero2:"Nicht den Graph.",hero:"Füge ein öffentliches GitHub-Repository ein. AVGL überführt begrenzte Evidence in eine verständliche System-Story, eine hierarchische Repository-Ansicht und einen Evidence-gebundenen Assistant.",repo:"GitHub-Repository",analyze:"Analysieren",help:"v0.2 analysiert öffentliche GitHub-Repositories. Private Repository-Authentifizierung ist noch nicht aktiviert.",analysis:"Analyse",story:"Story",files:"Files",inspect:"Inspect",system:"System",filesTitle:"Repository-Struktur",filesIntro:"Navigiere hierarchisch durch das Repository. Wähle ein File für eine verständliche Beschreibung von Rolle, Inhalt und möglicher Wirkung.",search:"Files durchsuchen…",select:"File auswählen",selectHint:"AVGL erklärt Inhalt, Rolle und die berührten semantischen Bereiche.",excerpt:"Source-Auszug",ask:"AVGL fragen",assistant:"Repository-Assistant",noRepo:"Analysiere zuerst ein Repository. Danach antwortet der Assistant auf Basis des aktuellen Repo-Context.",placeholder:"Frage zu Architektur, einem File, Permissions, Runtime…",send:"Senden",loading:"Repository-Evidence wird entdeckt, gebunden und synthetisiert…",done:"Analyse abgeschlossen. Signale bleiben begrenzt; Unbekanntes bleibt explizit.",loadFiles:"Repository-Hierarchie wird geladen…",filesFail:"Repository-Hierarchie konnte nicht geladen werden.",fileLoad:"File-Context wird geladen…",fileFail:"File-Context konnte nicht geladen werden.",role:"Rolle",areas:"Semantische Bereiche",symbols:"Symbole / Exports",lines:"Zeilen",size:"Größe",source:"Source-Surfaces",notFound:"Nicht belegt",partial:"Partieller begrenzter Scan",complete:"Vollständiger begrenzter Scan",systemNote:"Semantischer Rahmen, keine rekonstruierte Topologie. v0.2 extrahiert noch keine vollständigen Relation-/Call-Pfade.",evidenceIntro:"Statische Signale nach semantischem Bereich. Dokumentation kann Verständnis stützen, beweist allein aber weder MAY, ACT noch DID.",thinking:"Relevanter Repository-Context wird gelesen…",chatFail:"Der Assistant konnte diese Anfrage nicht beantworten.",keyMissing:"OpenRouter ist nicht konfiguriert. OPENROUTER_API_KEY muss in Vercel gesetzt werden.",suggest1:"Was sind die größten Architektur-Gaps?",suggest2:"Erkläre das Authority-Modell.",suggest3:"Welche Files sind für das Runtime-Verhalten am wichtigsten?",canMay:"Technische Reichweite ist keine Permission.",actDid:"Ein Effect-Pfad ist noch kein verifiziertes Ergebnis.",unknown:"Fehlende Evidence wird niemals durch eine Vermutung ersetzt.",scanModeLabel:"Scan-Modus",scanFull:"Vollständig",scanQuick:"Schnell · 120",scanFullHint:"Scannt jede geeignete Text-/Code-Datei im vollständigen Git-Tree.",scanQuickHint:"Schneller gewichteter Sample-Scan mit maximal 120 geeigneten Files.",sampled:"Files gescannt",fullScan:"Full Source Scan",quickScan:"Quick Sample"}
};
const Q={en:{WHO:"Who is acting?",KNOW:"What does it work with?",THINK:"How does it think or plan?",CAN:"What can it technically reach?",MAY:"What is it allowed to do?",ACT:"Where can real effects happen?",DID:"How is the result evidenced?"},de:{WHO:"Wer handelt?",KNOW:"Womit arbeitet das System?",THINK:"Wie denkt oder plant es?",CAN:"Was kann es technisch erreichen?",MAY:"Was darf es?",ACT:"Wo kann reale Wirkung entstehen?",DID:"Wie wird das Ergebnis nachgewiesen?"}};
const PREFIX={en:{WHO:"Agent structure",KNOW:"Context surfaces",THINK:"Cognition signals",CAN:"Capability surfaces",MAY:"Authority controls",ACT:"Effect paths",DID:"Evidence paths"},de:{WHO:"Agent-Struktur",KNOW:"Context-Surfaces",THINK:"Cognition-Signale",CAN:"Capability-Surfaces",MAY:"Authority-Controls",ACT:"Effect-Pfade",DID:"Evidence-Pfade"}};
const FAMILY_DE={"agent-definitions":"Agent-Definitionen","harness-instructions":"Harness / Instructions","roles":"Rollen","memory":"Memory","retrieval-rag":"Retrieval / RAG","context-state":"Context / State","resources-files":"Resources / Files","planning":"Planning / Replanning","reasoning":"Reasoning","delegation":"Handoffs / Subagents","routing":"Model- / Task-Routing","model-runtime":"Model-Runtime","filesystem":"Filesystem","browser-web":"Browser / Web","shell-process":"Shell / Process","function-tools":"Function Tools","database-storage":"Database / Storage","git-repository":"Git / Repository","messaging":"Messaging / E-Mail","authorization-policy":"Authorization / Policy","approval-hitl":"Approval / Human Control","permission-scope":"Permissions / Scope","grants-delegation":"Grants / Delegation","revocation-expiry":"Revocation / Expiry","executor-dispatch":"Executor / Dispatch","file-mutation":"File-Mutation","git-mutation":"Git-Mutation","network-send":"Network / API-Dispatch","deployment":"Deployment","database-mutation":"Database-Mutation","command-execution":"Command-Execution","verification":"Verification","receipts":"Receipts","audit-logging":"Audit / Logging","tests":"Tests","tracing-observability":"Tracing / Observability","reconciliation":"Reconciliation","outcomes":"Outcomes / Results"};
function t(k){return TXT[state.locale][k]||TXT.en[k]||k}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function nodeFor(c){return state.ir?.nodes?.find(n=>n.semanticClass===c)||null}
function areaFor(c){return state.ir?.synthesis?.areas?.[c]||null}
function famLabel(f){return state.locale==="de"?(FAMILY_DE[f.id]||f.label):f.label}
function summary(c){const a=areaFor(c),n=nodeFor(c);if(!a||a.status!=="EVIDENCED")return t("notFound");const labels=(a.families||[]).map(famLabel);return (PREFIX[state.locale][c]||c)+": "+(labels.length?labels.join(", "):(n?.label||"bounded signals"))+"."}
function fmtBytes(v){v=Number(v||0);return v<1024?v+" B":v<1048576?(v/1024).toFixed(1)+" KB":(v/1048576).toFixed(1)+" MB"}
function chip(text,cls=""){return el("span","chip "+cls,text)}
function applyLocale(){
 document.documentElement.lang=state.locale;$("#lang-toggle").textContent=state.locale==="de"?"EN":"DE";
 const map={heroLine1:"hero1",heroLine2:"hero2",heroCopy:"hero",repoLabel:"repo",analyzeBtn:"analyze",repoHelp:"help",analysisEyebrow:"analysis",tabStory:"story",tabFiles:"files",tabInspect:"inspect",tabSystem:"system",filesTitle:"filesTitle",filesIntro:"filesIntro",selectFile:"select",selectFileHint:"selectHint",sourceExcerpt:"excerpt",fabText:"ask",assistantTitle:"assistant",assistantContext:"noRepo",assistantSend:"send",scanModeLabel:"scanModeLabel",scanFull:"scanFull",scanQuick:"scanQuick"};
 for(const [id,key] of Object.entries(map)){const n=$("#"+id);if(n)n.textContent=t(key)}
 $("#file-search").placeholder=t("search");$("#assistant-input").placeholder=t("placeholder");$("#scan-mode-hint").textContent=t(state.scanStrategy==="full"?"scanFullHint":"scanQuickHint");
 if(state.ir){renderAll(false)} if(state.inventory)renderTree();if(state.activeFile)loadFile(state.activeFile,true);renderSuggestions();updateAssistantContext();
}
$("#lang-toggle").onclick=()=>{state.locale=state.locale==="de"?"en":"de";localStorage.setItem("avgl.locale",state.locale);applyLocale()};
function setScanStrategy(mode){state.scanStrategy=mode==="bounded"?"bounded":"full";document.querySelectorAll(".scan-mode-button").forEach(b=>b.classList.toggle("active",b.dataset.scan===state.scanStrategy));$("#scan-mode-hint").textContent=t(state.scanStrategy==="full"?"scanFullHint":"scanQuickHint")}
document.querySelectorAll(".scan-mode-button").forEach(b=>b.onclick=()=>setScanStrategy(b.dataset.scan));
function renderStory(){
 const host=$("#story-view");host.replaceChildren();const stack=el("div","story-stack");
 ["WHO","KNOW","THINK"].forEach((c,i)=>stack.append(storyStep(c,i+1)));
 const pair=el("div","capability-pair");pair.append(areaCard("CAN"),areaCard("MAY"));stack.append(pair,storyStep("ACT",4),storyStep("DID",5));host.append(stack)
}
function storyStep(c,i){const n=nodeFor(c),a=areaFor(c),w=el("div","story-step"+(n?"":" unknown"));w.append(el("div","story-number",String(i)));const body=el("div"),q=el("div","story-question");q.append(el("span","token",c),document.createTextNode(" · "+Q[state.locale][c]));body.append(q,el("p","story-answer",summary(c)),el("p","story-explain",n?sourceText(n):t("notFound")));if(a?.families?.length)body.append(familyRow(a));w.append(body);return w}
function areaCard(c){const a=areaFor(c),n=nodeFor(c),card=el("div","pair-card"+(!n&&c==="MAY"?" authority-missing":""));card.append(el("span","token",c),el("h3","",summary(c)),el("p","",n?sourceText(n):t("notFound")));if(a?.families?.length)card.append(familyRow(a));return card}
function familyRow(a){const r=el("div","family-row");(a.families||[]).forEach(f=>r.append(chip(famLabel(f),"family")));return r}
function sourceText(n){const kinds=[...new Set((n.evidence||[]).map(e=>e.sourceKind).filter(Boolean))];return t("source")+": "+(kinds.join(", ")||"unknown")}
function renderInspect(){
 const host=$("#inspect-view");host.replaceChildren(el("div","notice",t("evidenceIntro")));const grid=el("div","inspect-grid");
 for(const c of ["WHO","KNOW","THINK","CAN","MAY","ACT","DID"]){const n=nodeFor(c),card=el("article","inspect-card"),head=el("div","inspect-head");head.append(el("div","token",c),chip(n?.evidenceState||"UNKNOWN"));card.append(head,el("h3","",Q[state.locale][c]),el("p","",summary(c)));if(n?.evidence?.length){const d=el("details"),shown=n.evidence.length,total=n.evidenceCount??shown,s=el("summary","",shown===total?total+" evidence refs":shown+" / "+total+" evidence refs shown"),list=el("div","evidence-list");d.append(s);n.evidence.forEach(e=>{const item=el("div","evidence-item"),b=el("button","evidence-link",e.path+":"+e.line);b.onclick=()=>{selectView("files");loadFile(e.path)};item.append(b,chip(e.sourceKind||"unknown"),el("code","",e.snippet||""));list.append(item)});d.append(list);card.append(d)}grid.append(card)}host.append(grid)
}
function renderSystem(){const h=$("#system-view");h.replaceChildren(el("div","notice",t("systemNote")));const s=el("div","system-story");s.append(band("WHO · KNOW · THINK",state.locale==="de"?"Agent-Plane":"Agent plane",summary("WHO")+" · "+summary("KNOW")+" · "+summary("THINK")),arrow(),band("PROPOSAL",state.locale==="de"?"Intent verlässt Cognition":"Intent leaves cognition",state.locale==="de"?"Ein Model-Vorschlag ist noch keine Authority oder externer Effect.":"A model proposal is not yet authority or an external effect."),boundary());const p=el("div","system-pair");p.append(band("CAN",summary("CAN"),t("canMay")),band("MAY",summary("MAY"),t("canMay")));s.append(p,arrow(),band("ACT",summary("ACT"),t("actDid")),arrow(),band("DID",summary("DID"),t("actDid")));h.append(s)}
function band(tok,title,copy){const b=el("div","system-band");b.append(el("span","token",tok),el("h3","",title),el("p","",copy));return b}function arrow(){return el("div","system-arrow","↓")}function boundary(){return el("div","system-boundary",state.locale==="de"?"Authority Boundary":"Authority boundary")}
function renderMeta(){const a=state.ir.analysis||{},c=a.sourceCoverage||{},eligible=a.filesEligible??a.filesSeen;const h=$("#scan-meta"),mode=a.scanStrategy==="full"?t("fullScan"):t("quickScan");h.replaceChildren(chip(mode),chip((a.filesScanned||0)+"/"+eligible+" "+t("sampled")),chip("impl "+(c.implementation||0)+" · cfg "+(c.config||0)+" · test "+(c.test||0)+" · docs "+(c.documentation||0)),chip(a.scanComplete?t("complete"):t("partial")));const n=$("#partial-warning");n.hidden=!!a.scanComplete;if(!n.hidden){const failures=a.contentFetchFailures?.length||0;n.textContent=state.locale==="de"?`Scan unvollständig: ${a.filesScanned||0} von ${eligible} geeigneten Files gelesen${failures?`; ${failures} Fetch-Fehler`:""}. Nicht gelesene Evidence bleibt unbekannt.`:`Scan incomplete: ${a.filesScanned||0} of ${eligible} eligible files read${failures?`; ${failures} fetch failures`:""}. Unseen evidence remains unknown.`}}
function renderAll(scroll=true){$("#result-title").textContent=state.ir?.source?.label||state.repo;renderMeta();renderStory();renderInspect();renderSystem();$("#result").hidden=false;if(scroll)$("#result").scrollIntoView({behavior:"smooth",block:"start"})}
function selectView(v){document.querySelectorAll(".view-tab").forEach(b=>{const on=b.dataset.view===v;b.classList.toggle("active",on);b.setAttribute("aria-selected",String(on))});["story","files","inspect","system"].forEach(x=>$("#"+x+"-view").hidden=x!==v)}
document.querySelectorAll(".view-tab").forEach(b=>b.onclick=()=>selectView(b.dataset.view));

function buildTree(files){const root={dirs:new Map,files:[]};for(const file of files){let n=root;const parts=file.path.split("/");parts.forEach((p,i)=>{if(i===parts.length-1)n.files.push(file);else{if(!n.dirs.has(p))n.dirs.set(p,{name:p,dirs:new Map,files:[]});n=n.dirs.get(p)}})}return root}
function countTree(n){let c=n.files.length;for(const d of n.dirs.values())c+=countTree(d);return c}
function renderTreeNode(n,host,depth=0){[...n.dirs.values()].sort((a,b)=>a.name.localeCompare(b.name)).forEach(d=>{const details=el("details","tree-folder");if(depth<1)details.open=true;const s=el("summary","tree-folder-summary");s.append(el("span","chev","›"),el("span","",d.name),chip(String(countTree(d))));details.append(s);const ch=el("div","tree-children");renderTreeNode(d,ch,depth+1);details.append(ch);host.append(details)});n.files.sort((a,b)=>a.path.localeCompare(b.path)).forEach(f=>{const b=el("button","tree-file"+(state.activeFile===f.path?" active":""),f.path.split("/").pop());b.title=f.path;const meta=el("span","file-meta");meta.append(el("i","kind-dot "+f.sourceKind));if(evidencePaths().has(f.path))meta.append(el("b","evmark","E"));b.append(meta);b.onclick=()=>loadFile(f.path);host.append(b)})}
function evidencePaths(){return new Set((state.ir?.nodes||[]).flatMap(n=>(n.evidence||[]).map(e=>e.path)))}
function renderTree(){if(!state.inventory)return;const q=$("#file-search").value.trim().toLowerCase(),all=state.inventory.files||[],files=q?all.filter(f=>f.path.toLowerCase().includes(q)):all;$("#file-count").textContent=files.length+" "+t("fileCount");const h=$("#file-tree");h.replaceChildren();renderTreeNode(buildTree(files),h);$("#tree-warning").hidden=!state.inventory.treeTruncated;if(state.inventory.treeTruncated)$("#tree-warning").textContent=state.locale==="de"?"GitHub lieferte einen gekürzten Repository-Tree.":"GitHub returned a truncated repository tree."}
$("#file-search").oninput=renderTree;
async function loadInventory(repo){try{const r=await fetch("/api/repository",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repository:repo})}),p=await r.json();if(!r.ok)throw Error(p.error||t("filesFail"));state.inventory=p;renderTree();return p}catch(e){$("#tree-warning").hidden=false;$("#tree-warning").textContent=e.message;return null}}
async function loadFile(path,quiet=false){if(!state.repo)return;state.activeFile=path;renderTree();$("#file-empty").hidden=true;$("#file-detail").hidden=false;$("#file-role").textContent=t("fileLoad");$("#file-path").textContent=path;updateAssistantContext();try{const r=await fetch("/api/file",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repository:state.repo,path})}),p=await r.json();if(!r.ok)throw Error(p.error||t("fileFail"));showFile(p.file)}catch(e){$("#file-role").textContent=t("fileFail");$("#file-summary").textContent=e.message}}
function showFile(f){$("#file-role").textContent=f.role?.[state.locale]||f.sourceKind;$("#file-path").textContent=f.path;$("#file-summary").textContent=f.summary?.[state.locale]||"";const tags=$("#file-tags");tags.replaceChildren(chip(f.sourceKind));(f.semanticClasses||[]).forEach(c=>tags.append(chip(c,"semantic")));const facts=$("#file-facts");facts.replaceChildren(fact(t("role"),f.role?.[state.locale]||f.sourceKind),fact(t("areas"),(f.semanticClasses||[]).join(" · ")||"—"),fact(t("symbols"),(f.symbols||[]).join(", ")||"—"),fact(t("lines"),String(f.lineCount||"—")),fact(t("size"),fmtBytes(f.size)));$("#file-excerpt").textContent=f.excerpt||""}
function fact(k,v){const d=el("div","file-fact");d.append(el("span","",k),el("strong","",v));return d}

$("#analyze-form").onsubmit=async e=>{e.preventDefault();const repo=$("#repository").value.trim();if(!repo)return;state.repo=repo;state.ir=null;state.inventory=null;state.activeFile=null;state.chat=[];$("#error").hidden=true;$("#status").textContent=t("loading");$("#analyze-button").disabled=true;try{const [r]=await Promise.all([fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repository:repo,scanStrategy:state.scanStrategy})}),loadInventory(repo)]);const p=await r.json();if(!r.ok)throw Error(p.error||"Analysis failed");state.ir=p.ir;renderAll();$("#status").textContent=t("done");renderSuggestions();updateAssistantContext()}catch(err){$("#error").textContent=err.message;$("#error").hidden=false;$("#status").textContent=""}finally{$("#analyze-button").disabled=false}};
$("#assistant-fab").onclick=()=>{$("#assistant-panel").hidden=!$("#assistant-panel").hidden;if(!$("#assistant-panel").hidden)$("#assistant-input").focus()};$("#assistant-close").onclick=()=>$("#assistant-panel").hidden=true;
function updateAssistantContext(){const n=$("#assistant-context");if(!state.repo){n.textContent=t("noRepo");$("#assistant-send").disabled=true}else{n.textContent=state.repo+(state.activeFile?" · "+(state.locale==="de"?"Aktives File":"Active file")+": "+state.activeFile:"");$("#assistant-send").disabled=false}}
function renderSuggestions(){const h=$("#assistant-suggestions");h.replaceChildren();["suggest1","suggest2","suggest3"].forEach(k=>{const b=el("button","assistant-suggestion",t(k));b.type="button";b.onclick=()=>{$("#assistant-input").value=t(k);$("#assistant-input").focus()};h.append(b)})}
function bubble(role,text,meta=""){const m=el("div","chat-message "+role);m.append(el("div","chat-bubble",text));if(meta)m.append(el("div","chat-meta",meta));$("#assistant-messages").append(m);$("#assistant-messages").scrollTop=$("#assistant-messages").scrollHeight}
$("#assistant-form").onsubmit=async e=>{e.preventDefault();const q=$("#assistant-input").value.trim();if(!q||!state.repo)return;bubble("user",q);$("#assistant-input").value="";$("#assistant-send").disabled=true;$("#assistant-status").textContent=t("thinking");const history=state.chat.slice(-8);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repository:state.repo,question:q,locale:state.locale,activeFile:state.activeFile,history,context:state.ir})}),p=await r.json();if(!r.ok)throw Error(p.error||t("chatFail"));bubble("assistant",p.answer,p.model||"");state.chat.push({role:"user",content:q},{role:"assistant",content:p.answer})}catch(err){bubble("assistant",err.message.includes("not configured")?t("keyMissing"):err.message)}finally{$("#assistant-send").disabled=false;$("#assistant-status").textContent=""}};
setScanStrategy("full");applyLocale();renderSuggestions();updateAssistantContext();